#  see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
keys:
  - &user_homefree 06321D7F20335A7E08595BA905D137EE114BA2C2
  - &server_homefree 0BC4F8FF51F3167F06683FFB19008821C072983E
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *user_homefree
      - *server_homefree
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *user_homefree
      - *server_homefree
  - path_regex: secrets/homefree/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *user_homefree
      - *server_homefree
