- id: '1622943196790'
  alias: Outdoor String Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: time
    before: 00:00:00
    weekday:
    - fri
    - sat
    after: 00:00:00
  action:
  - type: turn_on
    device_id: 8246ac831671d63c51879e1ee50d69cb
    entity_id: switch.enbrighten_outdoor_plug
    domain: switch
  mode: single
- id: '1650844383208'
  alias: Outdoor String lights off
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: ' 03:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 8246ac831671d63c51879e1ee50d69cb
    entity_id: switch.enbrighten_outdoor_plug
    domain: switch
  mode: single
- id: '1651020392020'
  alias: PC Gaming On
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.pc_gaming_toggle
    to: 'on'
  - platform: state
    to: '0'
    entity_id: sensor.family_room_wallmote_scene_state_scene_001
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    target:
      device_id:
      - b68c253485f87e7e81bd57269b065af7
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.msi_desktop
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.lg_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.select_source
    data:
      source: hdmi1
    target:
      device_id: b68c253485f87e7e81bd57269b065af7
  mode: single
- id: '1651215506087'
  alias: Night Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - type: turn_on
    continue_on_error: true
    device_id: 8247817c078bd8302d4a8ac8b93b5715
    entity_id: light.leviton_light_switch
    domain: light
  - type: turn_on
    continue_on_error: true
    device_id: babe97eea14f5bcf483d05a33b9d8ae5
    entity_id: light.light_switch_2
    domain: light
    enabled: false
  - type: turn_on
    continue_on_error: true
    device_id: 2b41685d70f02bc1d532056b68dc5623
    entity_id: light.front_door_light
    domain: light
  - type: turn_on
    continue_on_error: true
    device_id: 79073a5a552a06399b8d5f9043f61e68
    entity_id: switch.node_14
    domain: switch
  - service: switch.turn_on
    continue_on_error: true
    data: {}
    target:
      entity_id: switch.front_door_light
    enabled: false
  - type: turn_on
    continue_on_error: true
    device_id: e4f0d27367975571cd815fc7a0f8c9ed
    entity_id: light.light_switch
    domain: light
  mode: single
- id: '1651215609427'
  alias: Night Lights Off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - type: turn_off
    continue_on_error: true
    device_id: 8247817c078bd8302d4a8ac8b93b5715
    entity_id: light.leviton_light_switch
    domain: light
  - type: turn_off
    continue_on_error: true
    device_id: 8246ac831671d63c51879e1ee50d69cb
    entity_id: switch.enbrighten_outdoor_plug
    domain: switch
  - type: turn_off
    continue_on_error: true
    device_id: babe97eea14f5bcf483d05a33b9d8ae5
    entity_id: light.light_switch_2
    domain: light
  - type: turn_off
    continue_on_error: true
    device_id: 2b41685d70f02bc1d532056b68dc5623
    entity_id: light.front_door_light
    domain: light
  - type: turn_off
    continue_on_error: true
    device_id: 79073a5a552a06399b8d5f9043f61e68
    entity_id: switch.node_14
    domain: switch
  - service: switch.turn_off
    continue_on_error: true
    data: {}
    target:
      entity_id: switch.front_door_light
    enabled: false
  - type: turn_off
    continue_on_error: true
    device_id: 2b41685d70f02bc1d532056b68dc5623
    entity_id: light.light_switch
    domain: light
  mode: single
- id: '1651610147639'
  alias: PC Gaming Off
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.pc_gaming_toggle
    to: 'off'
  - platform: state
    entity_id: sensor.family_room_wallmote_scene_state_scene_002
    to: '0'
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      device_id: b68c253485f87e7e81bd57269b065af7
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.lg_tv
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.msi_desktop
  mode: single
- id: '1652249662049'
  alias: Steam VR
  description: ''
  trigger: []
  condition: []
  action:
  - service: automation.trigger
    data: {}
    target:
      entity_id: automation.pc_gaming
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.stream_vr
  mode: single
- id: '1652423684248'
  alias: Garage Indoor Lights Off
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.light_switch
  mode: single
- id: '1662423684248'
  alias: ZWave - Ping Failed ZWaveJS Nodes
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.zwavejs_node_statistics
    attribute: Dead
    above: 0
    for:
      seconds: 10
  condition: []
  action:
  - service: zwave_js.ping
    target:
      entity_id: '{{ states | selectattr(''entity_id'', ''search'', ''_node_status'')
        | selectattr(''state'', ''in'', ''dead, unknown'') | map(attribute=''entity_id'')
        | list }}'
  - delay:
      minutes: 1
  mode: single
- id: '1662870152149'
  alias: ZWave - Check for dead nodes at start
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      minutes: 1
  - service: zwave_js.ping
    target:
      entity_id: '{{ states | selectattr(''entity_id'', ''search'', ''_node_status'')
        | selectattr(''state'', ''in'', ''dead, unknown'') | map(attribute=''entity_id'')
        | list }}'
  mode: single
- id: '1663168452995'
  alias: Office door left unlocked
  description: ''
  trigger:
  - platform: state
    entity_id:
    - lock.touchscreen_deadbolt_z_wave_plus
    to: unlocked
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Office door left unlocked
  mode: single
- id: '1663178807688'
  alias: Garage door left open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - cover.garage_door_controller
    to: open
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Garage door left open
  mode: single
- id: '1663287177862'
  alias: Front door left unlocked
  description: ''
  trigger:
  - platform: state
    entity_id:
    - lock.schlage_lock
    to: unlocked
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Front door left unlocked
  mode: single
- id: '1665369830899'
  alias: Turn off Living Room Lights
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 79073a5a552a06399b8d5f9043f61e68
    entity_id: switch.node_14
    domain: switch
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.front_door_light
  mode: single
- id: '1668475771304'
  alias: Backup - Full
  description: ''
  trigger:
  - platform: time
    at: 03:30:00
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: auto_backup.backup_full
    data:
      keep_days: 7
      exclude:
        folders:
        - /media/frigate/clips
        - /media/frigate/recordings
      compressed: true
  mode: single
- id: '1668475859645'
  alias: Backup - Purge Expired
  description: ''
  trigger:
  - platform: time
    at: 04:30:00
  condition: []
  action:
  - service: auto_backup.purge
    data: {}
  mode: single
- id: '1691356116704'
  alias: Backup - Partial
  description: ''
  trigger:
  - platform: time
    at: 03:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: auto_backup.backup_partial
    data:
      addons:
      - grafana
      - Configurator
      - core_mariadb
      compressed: true
  mode: single
